### ISSUE TITLE
0.1 released!

### ISSUE THREAD

**Issue by NalaGinrut** [NalaGinrut/guile-colorized#11]
Use (ice-9 format) to fix some crash issues.

**Comment by Profpatsch** [comment]
I moved to NixOS and have orphaned the Archlinux package.

**Comment by NalaGinrut** [comment]
Do you mean Guix? Or the original NixOS?

**Comment by Profpatsch** [comment]
Original NixOS. I still see no sense in Guix, apart from doing its own thing (and I’m not exactly convinced a strict language like Scheme makes any sense in that context).
